spring.application.name=Signalling-server
server.port=8080

server.ssl.enabled=true

server.ssl.key-store=file:${SSL_KEYSTORE}
server.ssl.key-store-password=${SSL_PASSWORD}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=spring

