spring.application.name=Signalling-server
server.port=8080

server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=palak123
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=spring

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

spring.data.mongodb.host=mongodb
spring.data.mongodb.port=27017

jwt.secret=palakdeepaksunitaumeshpalakdeepaksunitaumeshpalakdeepaksunitaumesh